const keyboardMap = {
    'a': 'C4',
    'w': 'C#4',
    's': 'D4',
    'e': 'D#4',
    'd': 'E4',
    'f': 'F4',
    't': 'F#4',
    'g': 'G4',
    'y': 'G#4',
    'h': 'A4',
    'u': 'A#4',
    'j': 'B4',
    'k': 'C5',
    'o': 'C#5',
    'l': 'D5',
    'p': 'D#5',
    ';': 'E5',
    "'": 'F5',
    ']': 'F#5',
    '\\': 'G5',
    '1': 'C#4',
    '2': 'D#4',
    '3': 'F#4',
    '4': 'G#4',
    '5': 'A#4',
    '6': 'C#5',
    '7': 'D#5',
    '8': 'F#5',
    '9': 'G#5',
    '0': 'A#5',
    'z': 'A5',
    'x': 'B5'
};

const pianoKeys = [
    { note: 'C4', type: 'white', key: 'A' },
    { note: 'C#4', type: 'black', key: 'W/1' },
    { note: 'D4', type: 'white', key: 'S' },
    { note: 'D#4', type: 'black', key: 'E/2' },
    { note: 'E4', type: 'white', key: 'D' },
    { note: 'F4', type: 'white', key: 'F' },
    { note: 'F#4', type: 'black', key: 'T/3' },
    { note: 'G4', type: 'white', key: 'G' },
    { note: 'G#4', type: 'black', key: 'Y/4' },
    { note: 'A4', type: 'white', key: 'H' },
    { note: 'A#4', type: 'black', key: 'U/5' },
    { note: 'B4', type: 'white', key: 'J' },
    { note: 'C5', type: 'white', key: 'K' },
    { note: 'C#5', type: 'black', key: 'O/6' },
    { note: 'D5', type: 'white', key: 'L' },
    { note: 'D#5', type: 'black', key: 'P/7' },
    { note: 'E5', type: 'white', key: ';' },
    { note: 'F5', type: 'white', key: "'" },
    { note: 'F#5', type: 'black', key: ']/8' },
    { note: 'G5', type: 'white', key: '\\' },
    { note: 'G#5', type: 'black', key: '9' },
    { note: 'A5', type: 'white', key: 'Z' },
    { note: 'A#5', type: 'black', key: '0' },
    { note: 'B5', type: 'white', key: 'X' }
];

function getNoteFromKey(key) {
    return keyboardMap[key.toLowerCase()] || null;
}
