const Themes = {
    classic: {
        name: '经典麻将',
        background: 'linear-gradient(135deg, #1B4D3E 0%, #0d2818 100%)',
        boardBackground: 'radial-gradient(ellipse at center, #2d5a46 0%, #1B4D3E 100%)',
        tileBackground: 'linear-gradient(145deg, #fff8e7 0%, #f5e6c8 50%, #e8d4a8 100%)',
        tileBorder: '#c9b896',
        accentColor: '#D4AF37',
        tileTypes: [
            { type: 'wan', value: 1, display: '一万', color: '#C41E3A' },
            { type: 'wan', value: 2, display: '二万', color: '#C41E3A' },
            { type: 'wan', value: 3, display: '三万', color: '#C41E3A' },
            { type: 'wan', value: 4, display: '四万', color: '#C41E3A' },
            { type: 'wan', value: 5, display: '五万', color: '#C41E3A' },
            { type: 'wan', value: 6, display: '六万', color: '#C41E3A' },
            { type: 'wan', value: 7, display: '七万', color: '#C41E3A' },
            { type: 'wan', value: 8, display: '八万', color: '#C41E3A' },
            { type: 'wan', value: 9, display: '九万', color: '#C41E3A' },
            { type: 'tiao', value: 1, display: '一条', color: '#228B22' },
            { type: 'tiao', value: 2, display: '二条', color: '#228B22' },
            { type: 'tiao', value: 3, display: '三条', color: '#228B22' },
            { type: 'tiao', value: 4, display: '四条', color: '#228B22' },
            { type: 'tiao', value: 5, display: '五条', color: '#228B22' },
            { type: 'tiao', value: 6, display: '六条', color: '#228B22' },
            { type: 'tiao', value: 7, display: '七条', color: '#228B22' },
            { type: 'tiao', value: 8, display: '八条', color: '#228B22' },
            { type: 'tiao', value: 9, display: '九条', color: '#228B22' },
            { type: 'tong', value: 1, display: '一筒', color: '#1E90FF' },
            { type: 'tong', value: 2, display: '二筒', color: '#1E90FF' },
            { type: 'tong', value: 3, display: '三筒', color: '#1E90FF' },
            { type: 'tong', value: 4, display: '四筒', color: '#1E90FF' },
            { type: 'tong', value: 5, display: '五筒', color: '#1E90FF' },
            { type: 'tong', value: 6, display: '六筒', color: '#1E90FF' },
            { type: 'tong', value: 7, display: '七筒', color: '#1E90FF' },
            { type: 'tong', value: 8, display: '八筒', color: '#1E90FF' },
            { type: 'tong', value: 9, display: '九筒', color: '#1E90FF' },
            { type: 'feng', value: 1, display: '东', color: '#333' },
            { type: 'feng', value: 2, display: '南', color: '#333' },
            { type: 'feng', value: 3, display: '西', color: '#333' },
            { type: 'feng', value: 4, display: '北', color: '#333' },
            { type: 'jian', value: 1, display: '中', color: '#C41E3A' },
            { type: 'jian', value: 2, display: '发', color: '#228B22' },
            { type: 'jian', value: 3, display: '白', color: '#666' }
        ]
    },
    fruits: {
        name: '水果派对',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        boardBackground: 'radial-gradient(ellipse at center, #8b5cf6 0%, #667eea 100%)',
        tileBackground: 'linear-gradient(145deg, #fef3c7 0%, #fde68a 50%, #fcd34d 100%)',
        tileBorder: '#f59e0b',
        accentColor: '#fbbf24',
        tileTypes: [
            { type: 'fruit', value: 1, display: '🍎', color: '#dc2626' },
            { type: 'fruit', value: 2, display: '🍊', color: '#ea580c' },
            { type: 'fruit', value: 3, display: '🍋', color: '#ca8a04' },
            { type: 'fruit', value: 4, display: '🍇', color: '#7c3aed' },
            { type: 'fruit', value: 5, display: '🍓', color: '#db2777' },
            { type: 'fruit', value: 6, display: '🍑', color: '#f472b6' },
            { type: 'fruit', value: 7, display: '🍒', color: '#dc2626' },
            { type: 'fruit', value: 8, display: '🥝', color: '#65a30d' },
            { type: 'fruit', value: 9, display: '🍌', color: '#eab308' },
            { type: 'fruit', value: 10, display: '🍉', color: '#22c55e' },
            { type: 'fruit', value: 11, display: '🥭', color: '#f97316' },
            { type: 'fruit', value: 12, display: '🍍', color: '#eab308' }
        ]
    },
    festival: {
        name: '节日庆典',
        background: 'linear-gradient(135deg, #dc2626 0%, #991b1b 100%)',
        boardBackground: 'radial-gradient(ellipse at center, #ef4444 0%, #dc2626 100%)',
        tileBackground: 'linear-gradient(145deg, #fef2f2 0%, #fee2e2 50%, #fecaca 100%)',
        tileBorder: '#f87171',
        accentColor: '#fbbf24',
        tileTypes: [
            { type: 'festival', value: 1, display: '🎆', color: '#dc2626' },
            { type: 'festival', value: 2, display: '🎇', color: '#f59e0b' },
            { type: 'festival', value: 3, display: '🧧', color: '#dc2626' },
            { type: 'festival', value: 4, display: '🎊', color: '#f59e0b' },
            { type: 'festival', value: 5, display: '🎉', color: '#22c55e' },
            { type: 'festival', value: 6, display: '🏮', color: '#dc2626' },
            { type: 'festival', value: 7, display: '🎁', color: '#7c3aed' },
            { type: 'festival', value: 8, display: '🎈', color: '#ec4899' },
            { type: 'festival', value: 9, display: '✨', color: '#fbbf24' },
            { type: 'festival', value: 10, display: '🌟', color: '#fbbf24' },
            { type: 'festival', value: 11, display: '💫', color: '#8b5cf6' },
            { type: 'festival', value: 12, display: '🎀', color: '#ec4899' }
        ]
    },
    animals: {
        name: '萌宠乐园',
        background: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
        boardBackground: 'radial-gradient(ellipse at center, #10b981 0%, #059669 100%)',
        tileBackground: 'linear-gradient(145deg, #ecfdf5 0%, #d1fae5 50%, #a7f3d0 100%)',
        tileBorder: '#34d399',
        accentColor: '#fbbf24',
        tileTypes: [
            { type: 'animal', value: 1, display: '🐱', color: '#f59e0b' },
            { type: 'animal', value: 2, display: '🐶', color: '#92400e' },
            { type: 'animal', value: 3, display: '🐰', color: '#fecaca' },
            { type: 'animal', value: 4, display: '🐼', color: '#1f2937' },
            { type: 'animal', value: 5, display: '🦊', color: '#ea580c' },
            { type: 'animal', value: 6, display: '🐨', color: '#6b7280' },
            { type: 'animal', value: 7, display: '🦁', color: '#f59e0b' },
            { type: 'animal', value: 8, display: '🐯', color: '#f97316' },
            { type: 'animal', value: 9, display: '🐸', color: '#22c55e' },
            { type: 'animal', value: 10, display: '🐧', color: '#1f2937' },
            { type: 'animal', value: 11, display: '🐤', color: '#fbbf24' },
            { type: 'animal', value: 12, display: '🦄', color: '#ec4899' }
        ]
    }
};
